- README.md
- about_section_text
Added About Section
Added a space
> Liao21 about section

- .gitignore
- README.md
- smap/.codecov.yml
- smap/.travis.yml
- smap/package.json
Travis.ci and Codecov integration
> Bunger travis

- smap/public/javascripts/visuals.js
Details time to load and time to page accessibility using window.performance
Note: this is the bare minimum for the sprint, but I want to get this merged in now, will look into more things later each statistic selection.
> robinsph21 performance metrics

- .travis.yml
Fixed bug in deployment where passwords.json was not uploaded from Travis
> Gcloud app

- smap/public/index.html
- smap/public/javascripts/visuals.js
- smap/public/stylesheets/style.css
Somehow, a bug with the sliding effects got into master.
> Added in legend for map visualization and fixed sliding JS

- smap/public/stylesheets/style.css
QOL change to make the UI act more like a proper UI
> Make nav bar non-selectable

- smap/public/index.html
- smap/public/javascripts/visuals.js
- smap/public/stylesheets/style.css
Since google and other providers won't actually allow us to have ads, we are just adding in basic place-holders for where ads would go and hoping that's enough.
> Adding in mock ads

- smap/public/index.html
- smap/public/javascripts/visuals.js
Fixes #41 by changing DOM properties rather than HTML properties.
> Race cond fix

- smap/public/javascripts/visuals.js
- smap/public/stylesheets/style.css
Updated to take care of IDE annoyance and cleared console flooding.
> Quick changes

- smap/public/javascripts/visuals.js
Note that this addresses issue #73; can resolve that upon merge
> Styling now consistant when no stats selected

- smap/public/javascripts/model.js
> Fixed issue with latest added category not being saved

- README.md
- smap/routes/api.js
- smap/routes/imports/apiHandler.js
- smap/tests/apiHandler.test.js
- smap/tests/security_report.txt
Includes a couple of new tests for apiHandler, a brief description in the README, and a more detailed file.
> Security report

- smap/public/index.html
- smap/public/stylesheets/style.css
If I never see another tick mark, it will be too soon.
> Slider side scrolling and text-wrapping for long stat titles

- smap/public/javascripts/visuals.js
- smap/routes/api.js
Retyped an apostrophe and reuploaded the Reported Violent Crime Rate note back into metadata3. I don't think any code was changed which makes me a little sad.
> Retyped an apostrophe

- smap/public/index.html
- smap/public/javascripts/visuals.js
- smap/public/stylesheets/style.css
Changing all the functions to be in a more testable, more organized state.
> Visuals reorganization

- smap/public/stylesheets/style.css
It appears on edge the default width is not auto... changing this fixes #58
> Fix slider widths on Edge

- .travis.yml
- smap/package.json
- smap/public/index.html
- smap/public/javascripts/model.js
- smap/tests/client/model.test.js
model.js is effectively 100% covered. The only gaps are where we check if we can export the functions and if localStorage is available. Neither case can be tested, but the former doesn't need to be and the latter is an abnormally rare case.
> Client side tests ryan

- smap/public/javascripts/model.js
- smap/tests/client/model.test.js
and fixed Ryan's spelling error mwaahahaha
> Added some Most Inventive Test (MIT) comments 

- smap/public/javascripts/model.js
- smap/public/javascripts/visuals.js
- smap/routes/imports/constants.js
- smap/tests/apiHandler.test.js
- smap/tests/client/model.test.js
Shows state value and ranks for best and worst statistic in state window.
Fixes #92
> Improved state window.

- smap/public/javascripts/model.js
- smap/public/javascripts/visuals.js
- smap/tests/acceptanceTests.txt
- smap/tests/client/model.test.js
All verified for firefox, chrome, safari, edge and all mobile versions for these browsers.
> Acceptance tests

- README.md
> Added in cross browser compatibility notes
